export const FIXED_TICK_RATE = 20;
export const FIXED_TICK_MS = 1000 / FIXED_TICK_RATE;
export const DEFAULT_PLAYER_MAX_HP = 10000;
export const DEFAULT_PLAYER_MOVE_SPEED = 6;
export const KNOCKBACK_IMMUNE_COOLDOWN_MS = 20_000;
export const KNOCKBACK_IMMUNE_DURATION_MS = 8_000;
export const INJURY_UP_DURATION_MS = 1_000;
export const INJURY_UP_MULTIPLIER = 10;
